// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: G:/ObligatorioTC/jflex-1.9.1/examples/cup-interpreter/src/main/jflex/RecetarioLexer.flex

/* ========= RecetarioLexer.flex ========= */
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
class RecetarioLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\37\u0200"+
    "\1\u0600\u1000\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\0\1\7\1\10\6\0\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\11\17\1\20\2\0\1\21\3\0"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\33\1\42\1\43\1\44\1\45\4\33\1\46\1\47"+
    "\1\50\1\51\1\0\1\33\1\0\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\33\1\42\1\43"+
    "\1\44\1\45\4\33\1\46\12\0\1\3\33\0\1\33"+
    "\7\0\1\33\3\0\1\33\3\0\1\33\1\0\1\33"+
    "\6\0\1\33\1\0\1\33\6\0\1\52\37\0\1\53"+
    "\114\0\2\54\41\0\1\33\15\0\1\33\35\0\1\55"+
    "\u0198\0\1\33\3\0\1\33\13\0\2\3\6\0\1\33"+
    "\371\0\1\56\325\0\u0100\3\375\0\1\57\2\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1792];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\1\2\10\1\11\1\12\4\13\1\14\7\13"+
    "\1\15\1\16\2\1\3\0\1\4\1\0\1\17\2\0"+
    "\1\20\1\0\1\21\3\22\1\4\5\13\1\0\1\13"+
    "\1\14\7\13\2\0\1\14\3\0\1\10\5\4\1\0"+
    "\1\4\2\23\1\4\1\0\1\4\1\0\5\4\3\0"+
    "\1\24\5\4\1\0\2\4\1\0\1\4\1\0\2\4"+
    "\1\14\1\4\1\25\1\0\1\25\1\0\1\4\1\0"+
    "\4\4\1\0\2\4\1\0\2\26\1\4\1\0\2\4"+
    "\2\0\1\4\1\0\2\4\2\0\3\4\1\0\1\4"+
    "\2\27\1\4\1\0\1\30\2\31\1\0\2\32\1\4"+
    "\1\0\2\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\2\33\2\4\3\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0"+
    "\1\14\1\4\1\0\1\4\1\0\2\34\1\4\1\0"+
    "\2\35\2\36\1\4\1\0\1\4\1\0\1\4\1\0"+
    "\1\4\1\0\2\37\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\2\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\220\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\220\0\220\0\u01b0\0\u01e0\0\u0210\0\220"+
    "\0\220\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0270\0\u0300\0\u0330"+
    "\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420\0\220\0\220\0\u0450"+
    "\0\u0480\0\220\0\u04b0\0\u04e0\0\u0510\0\u0150\0\220\0\u0540"+
    "\0\u0570\0\u05a0\0\u05d0\0\u05d0\0\u0510\0\u0600\0\u0210\0\u0630"+
    "\0\220\0\u0510\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0510"+
    "\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0"+
    "\0\u08d0\0\220\0\u04e0\0\u0900\0\u0930\0\u05d0\0\u0960\0\u0990"+
    "\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0510\0\220\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0\0\u0c00\0\u0c30"+
    "\0\u0c60\0\u0c90\0\u0cc0\0\220\0\u0cf0\0\u0d20\0\u0d50\0\u0d80"+
    "\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00"+
    "\0\u0f30\0\u0f60\0\u0f90\0\u0510\0\u0fc0\0\220\0\u0ff0\0\u1020"+
    "\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0"+
    "\0\u11d0\0\u0510\0\220\0\u1200\0\u1230\0\u1260\0\u1290\0\u12c0"+
    "\0\u12f0\0\u1320\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440"+
    "\0\u1470\0\u14a0\0\u14d0\0\u1500\0\u0510\0\220\0\u1530\0\u1560"+
    "\0\u1590\0\u0510\0\220\0\u15c0\0\u0510\0\220\0\u15f0\0\u1620"+
    "\0\u1650\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u1740\0\u1770\0\u17a0"+
    "\0\u17d0\0\u1800\0\u1830\0\u0510\0\220\0\u1860\0\u1890\0\u18c0"+
    "\0\u18f0\0\u1920\0\u1950\0\u1980\0\u19b0\0\u19e0\0\u1a10\0\u1a40"+
    "\0\u1a70\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\u1b90\0\u1bc0"+
    "\0\u1bf0\0\u0510\0\220\0\u1c20\0\u1c50\0\u0510\0\220\0\u0510"+
    "\0\220\0\u1c80\0\u1cb0\0\u1ce0\0\u1d10\0\u1d40\0\u1d70\0\u1da0"+
    "\0\u1dd0\0\u0510\0\220\0\u1e00\0\u1e30\0\u1e60\0\u1e90\0\u1ec0"+
    "\0\u1ef0\0\u1f20\0\u1f50\0\u1f80\0\u1fb0\0\u1fe0\0\u2010\0\u2040"+
    "\0\u2070\0\u20a0\0\u20d0\0\u0510\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\0\1\5\1\7\1\10\1\11"+
    "\1\12\1\4\1\13\1\4\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\2\23\1\26"+
    "\1\23\1\27\1\23\1\30\1\26\1\31\1\23\1\32"+
    "\1\33\1\34\1\23\1\35\1\26\1\23\1\36\1\4"+
    "\1\37\1\23\1\4\1\40\1\4\1\41\1\23\16\0"+
    "\1\42\1\43\56\0\2\44\121\0\1\5\2\0\1\5"+
    "\1\0\1\5\53\0\1\6\56\0\1\5\2\0\1\5"+
    "\1\0\1\10\7\0\2\45\2\0\25\45\3\0\1\45"+
    "\4\0\1\45\2\46\1\0\2\46\1\0\1\46\1\47"+
    "\40\46\1\50\7\46\2\12\1\0\2\12\1\0\52\12"+
    "\11\0\1\51\3\0\1\52\50\0\1\45\3\0\1\53"+
    "\1\0\1\54\1\0\1\55\1\56\2\0\25\45\3\0"+
    "\1\45\4\0\1\45\6\0\1\45\3\0\1\53\1\0"+
    "\1\54\1\0\2\57\2\0\25\45\3\0\1\45\4\0"+
    "\1\45\6\0\1\60\4\0\1\61\2\0\2\62\2\0"+
    "\25\62\3\0\1\62\4\0\1\62\6\0\1\45\4\0"+
    "\1\61\2\0\2\62\2\0\25\62\3\0\1\62\4\0"+
    "\1\62\6\0\1\45\4\0\1\61\2\0\2\62\2\0"+
    "\1\63\22\62\1\64\1\62\3\0\1\62\4\0\1\62"+
    "\6\0\1\45\4\0\1\61\2\0\2\62\2\0\10\62"+
    "\1\65\14\62\3\0\1\62\1\0\1\66\2\0\1\62"+
    "\6\0\1\45\4\0\1\61\2\0\2\62\2\0\15\62"+
    "\1\67\7\62\3\0\1\62\4\0\1\62\6\0\1\45"+
    "\4\0\1\61\2\0\2\62\2\0\6\62\1\70\16\62"+
    "\3\0\1\62\4\0\1\62\6\0\1\45\4\0\1\61"+
    "\2\0\2\62\2\0\13\62\1\70\11\62\3\0\1\62"+
    "\4\0\1\62\6\0\1\45\4\0\1\61\2\0\2\62"+
    "\2\0\1\62\1\71\16\62\1\72\4\62\3\0\1\62"+
    "\4\0\1\62\6\0\1\45\4\0\1\61\2\0\2\62"+
    "\2\0\1\73\15\62\1\74\6\62\3\0\1\62\4\0"+
    "\1\62\6\0\1\45\4\0\1\61\2\0\2\62\2\0"+
    "\4\62\1\75\20\62\3\0\1\62\4\0\1\62\6\0"+
    "\1\45\4\0\1\61\2\0\2\62\2\0\1\76\7\62"+
    "\1\77\14\62\3\0\1\62\1\0\1\100\2\0\1\62"+
    "\37\0\1\101\50\0\1\102\45\0\2\43\56\0\1\103"+
    "\1\44\46\0\1\45\7\0\2\45\2\0\25\45\3\0"+
    "\1\45\4\0\1\45\50\0\1\104\7\0\11\51\1\105"+
    "\46\51\2\52\1\0\2\52\1\0\52\52\16\0\2\106"+
    "\46\0\1\45\7\0\2\56\2\0\25\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\6\45"+
    "\1\107\16\45\3\0\1\45\4\0\1\45\6\0\1\45"+
    "\7\0\2\45\2\0\13\45\1\110\6\45\1\111\2\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\2\45\1\112\22\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\5\45\1\113\17\45"+
    "\3\0\1\45\4\0\1\45\27\0\1\114\36\0\1\45"+
    "\7\0\2\45\2\0\6\45\1\115\16\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\21\45"+
    "\1\116\3\45\3\0\1\45\2\0\1\117\1\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\10\45\1\120\14\45"+
    "\3\0\1\45\1\0\1\121\2\0\1\45\6\0\1\45"+
    "\7\0\2\45\2\0\21\45\1\122\3\45\3\0\1\45"+
    "\2\0\1\123\1\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\20\45\1\124\4\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\2\45\1\125\22\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\24\45\1\126\3\0\1\45\4\0\1\45\6\0"+
    "\1\45\7\0\2\45\2\0\4\45\1\127\12\45\1\130"+
    "\5\45\3\0\1\45\4\0\1\45\26\0\1\131\12\0"+
    "\1\132\46\0\1\133\27\0\2\46\4\0\52\46\11\51"+
    "\1\105\3\51\1\134\42\51\6\0\1\45\7\0\2\45"+
    "\2\0\23\45\1\135\1\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\16\45\1\136\6\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\4\45\1\137\20\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\7\45\1\140\15\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\10\45\1\141\14\45\3\0\1\45\1\0\1\142"+
    "\2\0\1\45\32\0\1\142\21\0\1\142\11\0\1\45"+
    "\7\0\2\45\2\0\20\45\1\143\4\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\6\45"+
    "\1\144\16\45\3\0\1\45\4\0\1\45\30\0\1\145"+
    "\35\0\1\45\7\0\2\45\2\0\16\45\1\146\6\45"+
    "\3\0\1\45\4\0\1\45\40\0\1\147\25\0\1\45"+
    "\7\0\2\45\2\0\2\45\1\150\22\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\4\45"+
    "\1\151\20\45\3\0\1\45\4\0\1\45\6\0\1\45"+
    "\7\0\2\45\2\0\1\152\24\45\3\0\1\45\4\0"+
    "\1\45\6\0\1\45\7\0\2\45\2\0\14\45\1\153"+
    "\10\45\3\0\1\45\4\0\1\45\6\0\1\45\7\0"+
    "\2\45\2\0\16\45\1\154\6\45\3\0\1\45\4\0"+
    "\1\45\36\0\1\155\61\0\1\156\61\0\1\157\23\0"+
    "\1\45\7\0\2\45\2\0\21\45\1\160\3\45\3\0"+
    "\1\45\2\0\1\161\1\0\1\45\6\0\1\45\7\0"+
    "\2\45\2\0\20\45\1\162\4\45\3\0\1\45\4\0"+
    "\1\45\6\0\1\45\7\0\2\45\2\0\6\45\1\163"+
    "\16\45\3\0\1\45\4\0\1\45\6\0\1\45\7\0"+
    "\2\45\2\0\1\164\24\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\2\45\1\165\22\45"+
    "\3\0\1\45\4\0\1\45\24\0\1\166\41\0\1\45"+
    "\7\0\2\45\2\0\4\45\1\167\20\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\4\45"+
    "\1\170\20\45\3\0\1\45\4\0\1\45\26\0\1\171"+
    "\37\0\1\45\7\0\2\45\2\0\21\45\1\172\3\45"+
    "\3\0\1\45\2\0\1\173\1\0\1\45\43\0\1\173"+
    "\11\0\1\173\10\0\1\45\7\0\2\45\2\0\10\45"+
    "\1\174\14\45\3\0\1\45\1\0\1\175\2\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\22\45\1\176\2\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\21\45\1\70\3\45\3\0\1\45\2\0\1\102"+
    "\1\0\1\45\6\0\1\45\7\0\2\45\2\0\17\45"+
    "\1\177\5\45\3\0\1\45\4\0\1\45\41\0\1\200"+
    "\44\0\1\201\37\0\1\45\7\0\2\45\2\0\22\45"+
    "\1\202\2\45\3\0\1\45\4\0\1\45\44\0\1\203"+
    "\21\0\1\45\7\0\2\45\2\0\10\45\1\204\14\45"+
    "\3\0\1\205\1\206\1\207\2\0\1\45\6\0\1\45"+
    "\7\0\2\45\2\0\16\45\1\210\6\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\20\45"+
    "\1\211\4\45\3\0\1\45\4\0\1\45\6\0\1\45"+
    "\7\0\2\45\2\0\23\45\1\212\1\45\3\0\1\45"+
    "\4\0\1\45\45\0\1\213\20\0\1\45\7\0\2\45"+
    "\2\0\3\45\1\214\21\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\15\45\1\215\7\45"+
    "\3\0\1\45\4\0\1\45\37\0\1\216\26\0\1\45"+
    "\7\0\2\45\2\0\16\45\1\217\6\45\3\0\1\45"+
    "\4\0\1\45\40\0\1\220\25\0\1\45\7\0\2\45"+
    "\2\0\1\221\24\45\3\0\1\45\4\0\1\45\6\0"+
    "\1\45\7\0\2\45\2\0\16\45\1\222\6\45\3\0"+
    "\1\45\4\0\1\45\40\0\1\223\44\0\1\224\40\0"+
    "\1\45\7\0\2\45\2\0\16\45\1\225\6\45\3\0"+
    "\1\45\4\0\1\45\40\0\1\226\25\0\1\45\7\0"+
    "\2\45\2\0\1\227\24\45\3\0\1\45\4\0\1\45"+
    "\6\0\1\45\7\0\2\45\2\0\25\45\3\0\1\45"+
    "\4\0\1\204\57\0\1\207\22\0\1\230\43\0\1\45"+
    "\7\0\2\45\2\0\20\45\1\231\4\45\3\0\1\45"+
    "\4\0\1\45\6\0\1\45\7\0\2\45\2\0\1\152"+
    "\7\45\1\232\14\45\3\0\1\45\1\0\1\233\2\0"+
    "\1\45\6\0\1\45\7\0\2\45\2\0\13\45\1\234"+
    "\11\45\3\0\1\45\4\0\1\45\35\0\1\235\30\0"+
    "\1\45\7\0\2\45\2\0\10\45\1\236\14\45\3\0"+
    "\1\45\1\0\1\237\2\0\1\45\6\0\1\45\7\0"+
    "\2\45\2\0\15\45\1\240\7\45\3\0\1\45\4\0"+
    "\1\45\37\0\1\241\26\0\1\45\7\0\2\45\2\0"+
    "\21\45\1\242\3\45\3\0\1\45\2\0\1\243\1\0"+
    "\1\45\32\0\1\237\21\0\1\237\11\0\1\45\7\0"+
    "\2\45\2\0\21\45\1\244\3\45\3\0\1\45\2\0"+
    "\1\245\1\0\1\45\43\0\1\245\11\0\1\245\10\0"+
    "\1\45\7\0\2\45\2\0\10\45\1\246\14\45\3\0"+
    "\1\247\1\250\1\251\2\0\1\45\6\0\1\45\7\0"+
    "\2\45\2\0\22\45\1\126\2\45\3\0\1\45\4\0"+
    "\1\45\44\0\1\252\21\0\1\45\7\0\2\45\2\0"+
    "\22\45\1\253\2\45\3\0\1\45\4\0\1\45\44\0"+
    "\1\254\21\0\1\45\7\0\2\45\2\0\4\45\1\255"+
    "\20\45\3\0\1\45\4\0\1\45\26\0\1\256\37\0"+
    "\1\45\7\0\2\45\2\0\4\45\1\257\20\45\3\0"+
    "\1\45\4\0\1\45\26\0\1\260\37\0\1\261\7\0"+
    "\2\45\2\0\25\45\3\0\1\45\4\0\1\45\6\0"+
    "\1\262\57\0\1\45\7\0\2\45\2\0\1\263\24\45"+
    "\3\0\1\45\4\0\1\45\6\0\1\45\7\0\2\45"+
    "\2\0\25\45\3\0\1\45\4\0\1\246\57\0\1\251"+
    "\22\0\1\264\57\0\1\265\43\0\1\45\7\0\2\45"+
    "\2\0\1\266\24\45\3\0\1\45\4\0\1\45\22\0"+
    "\1\267\43\0\1\45\7\0\2\45\2\0\15\45\1\270"+
    "\7\45\3\0\1\45\4\0\1\45\37\0\1\271\26\0"+
    "\1\45\7\0\2\45\2\0\21\45\1\272\3\45\3\0"+
    "\1\45\2\0\1\273\1\0\1\45\43\0\1\273\11\0"+
    "\1\273\10\0\1\261\7\0\2\45\2\0\20\45\1\274"+
    "\4\45\3\0\1\45\4\0\1\45\6\0\1\262\33\0"+
    "\1\275\23\0\1\45\7\0\2\45\2\0\21\45\1\276"+
    "\3\45\3\0\1\45\2\0\1\277\1\0\1\45\43\0"+
    "\1\277\11\0\1\277\45\0\1\102\11\0\1\102\10\0"+
    "\1\45\7\0\2\45\2\0\3\45\1\300\21\45\3\0"+
    "\1\45\4\0\1\45\25\0\1\301\40\0\1\45\7\0"+
    "\2\45\2\0\22\45\1\302\2\45\3\0\1\45\4\0"+
    "\1\45\44\0\1\303\21\0\1\45\7\0\2\45\2\0"+
    "\4\45\1\304\20\45\3\0\1\45\4\0\1\45\26\0"+
    "\1\305\37\0\1\45\7\0\2\45\2\0\4\45\1\306"+
    "\20\45\3\0\1\45\4\0\1\45\26\0\1\307\37\0"+
    "\1\45\7\0\2\45\2\0\13\45\1\310\11\45\3\0"+
    "\1\45\4\0\1\45\35\0\1\311\30\0\1\45\7\0"+
    "\2\45\2\0\21\45\1\312\3\45\3\0\1\45\2\0"+
    "\1\313\1\0\1\45\43\0\1\313\11\0\1\313\10\0"+
    "\1\45\7\0\2\45\2\0\1\314\24\45\3\0\1\45"+
    "\4\0\1\45\22\0\1\315\43\0\1\45\7\0\2\45"+
    "\2\0\2\45\1\316\22\45\3\0\1\45\4\0\1\45"+
    "\24\0\1\317\41\0\1\45\7\0\2\45\2\0\10\45"+
    "\1\320\14\45\3\0\1\45\1\0\1\321\2\0\1\45"+
    "\32\0\1\321\21\0\1\321\11\0\1\45\7\0\2\45"+
    "\2\0\16\45\1\322\6\45\3\0\1\45\4\0\1\45"+
    "\40\0\1\323\25\0\1\45\7\0\2\45\2\0\15\45"+
    "\1\324\7\45\3\0\1\45\4\0\1\45\37\0\1\325"+
    "\26\0\1\45\7\0\2\45\2\0\1\326\24\45\3\0"+
    "\1\45\4\0\1\45\22\0\1\327\43\0\1\45\7\0"+
    "\2\45\2\0\3\45\1\330\21\45\3\0\1\45\4\0"+
    "\1\45\25\0\1\331\40\0\1\45\7\0\2\45\2\0"+
    "\1\332\24\45\3\0\1\45\4\0\1\45\22\0\1\333"+
    "\43\0\1\45\7\0\2\45\2\0\21\45\1\334\3\45"+
    "\3\0\1\45\2\0\1\335\1\0\1\45\43\0\1\335"+
    "\11\0\1\335\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8448];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\2\11\3\1\2\11"+
    "\14\1\2\11\2\1\1\11\3\1\1\0\1\11\2\0"+
    "\1\1\1\0\5\1\1\11\4\1\1\0\11\1\2\0"+
    "\1\11\3\0\6\1\1\0\2\1\1\11\1\1\1\0"+
    "\1\1\1\0\5\1\3\0\1\11\5\1\1\0\2\1"+
    "\1\0\1\1\1\0\5\1\1\0\1\11\1\0\1\1"+
    "\1\0\4\1\1\0\2\1\1\0\1\1\1\11\1\1"+
    "\1\0\2\1\2\0\1\1\1\0\2\1\2\0\3\1"+
    "\1\0\2\1\1\11\1\1\1\0\2\1\1\11\1\0"+
    "\1\1\1\11\1\1\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\2\1\3\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\11\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** For the backwards DFA of general lookahead statements */
  private boolean [] zzFin = new boolean [Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())+1];

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  /* ===== Helpers ===== */
  private Symbol sym(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }
  private Symbol sym(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  // Unescape mínimo para strings: \" y \\ → " y \
  private String unescapeMin(String rawWithQuotes) {
    String inner = rawWithQuotes.substring(1, rawWithQuotes.length() - 1);
    inner = inner.replace("\\\\", "\\");
    inner = inner.replace("\\\"", "\"");
    return inner;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  RecetarioLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error(
      "Carácter inesperado '" + yytext() +
      "' en línea " + (yyline+1) +
      ", columna " + (yycolumn+1)
    );
            }
          // fall through
          case 33: break;
          case 2:
            { /* ignorar espacios */
            }
          // fall through
          case 34: break;
          case 3:
            { /* ignorar saltos de línea */
            }
          // fall through
          case 35: break;
          case 4:
            { return sym(sym.ID, yytext().trim());
            }
          // fall through
          case 36: break;
          case 5:
            { /* ignorar comentario tipo # */
            }
          // fall through
          case 37: break;
          case 6:
            { return sym(sym.COMMA);
            }
          // fall through
          case 38: break;
          case 7:
            { return sym(sym.DOT);
            }
          // fall through
          case 39: break;
          case 8:
            { if (yytext().contains(".") || yytext().contains(","))
         return sym(sym.DEC, yytext());
    else return sym(sym.INT, Integer.parseInt(yytext()));
            }
          // fall through
          case 40: break;
          case 9:
            { return sym(sym.COLON);
            }
          // fall through
          case 41: break;
          case 10:
            { return sym(sym.EQ);
            }
          // fall through
          case 42: break;
          case 11:
            { return sym(sym.ID, yytext());
            }
          // fall through
          case 43: break;
          case 12:
            { return sym(sym.UNIT, yytext());
            }
          // fall through
          case 44: break;
          case 13:
            { return sym(sym.LBRACK);
            }
          // fall through
          case 45: break;
          case 14:
            { return sym(sym.RBRACK);
            }
          // fall through
          case 46: break;
          case 15:
            { return sym(sym.STRING, unescapeMin(yytext()));
            }
          // fall through
          case 47: break;
          case 16:
            { /* ignorar comentario tipo // */
            }
          // fall through
          case 48: break;
          case 17:
            { String num = yytext().substring(0, yytext().length()-1);
    return sym(sym.STEPNUM, Integer.parseInt(num));
            }
          // fall through
          case 49: break;
          case 18:
            // general lookahead, find correct zzMarkedPos
            { int zzFState = 1;
              int zzFPos = zzStartRead;
              if (zzFin.length <= zzBufferL.length) {
                zzFin = new boolean[zzBufferL.length+1];
              }
              boolean zzFinL[] = zzFin;
              while (zzFState != -1 && zzFPos < zzMarkedPos) {
                zzFinL[zzFPos] = ((zzAttrL[zzFState] & 1) == 1);
                zzInput = Character.codePointAt(zzBufferL, zzFPos, zzMarkedPos);
                zzFPos += Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              }
              if (zzFState != -1) {
                zzFinL[zzFPos++] = ((zzAttrL[zzFState] & 1) == 1);
              }
              while (zzFPos <= zzMarkedPos) {
                zzFinL[zzFPos++] = false;
              }

              zzFState = 2;
              zzFPos = zzMarkedPos;
              while (!zzFinL[zzFPos] || (zzAttrL[zzFState] & 1) != 1) {
                zzInput = Character.codePointBefore(zzBufferL, zzFPos, zzStartRead);
                zzFPos -= Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              };
              zzMarkedPos = zzFPos;
            }
            { return sym(sym.FRAC, yytext());
            }
          // fall through
          case 50: break;
          case 19:
            { return sym(sym.OBS_KW);
            }
          // fall through
          case 51: break;
          case 20:
            { /* ignorar bloque */
            }
          // fall through
          case 52: break;
          case 21:
            { return sym(sym.TIPO_KW);
            }
          // fall through
          case 53: break;
          case 22:
            { return sym(sym.PASOS_KW);
            }
          // fall through
          case 54: break;
          case 23:
            { return sym(sym.ORIGEN_KW);
            }
          // fall through
          case 55: break;
          case 24:
            { return sym(sym.RECETA_KW);
            }
          // fall through
          case 56: break;
          case 25:
            { return sym(sym.TIEMPO_KW);
            }
          // fall through
          case 57: break;
          case 26:
            { return sym(sym.A_GUSTO);
            }
          // fall through
          case 58: break;
          case 27:
            { return sym(sym.CALORIAS_KW);
            }
          // fall through
          case 59: break;
          case 28:
            { return sym(sym.PORCIONES_KW);
            }
          // fall through
          case 60: break;
          case 29:
            { return sym(sym.CATEGORIAS_KW);
            }
          // fall through
          case 61: break;
          case 30:
            { return sym(sym.DIFICULTAD_KW);
            }
          // fall through
          case 62: break;
          case 31:
            { return sym(sym.INGREDIENTES_KW);
            }
          // fall through
          case 63: break;
          case 32:
            { return sym(sym.RELACIONADAS_KW);
            }
          // fall through
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
